Added mac specific conditionals

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 for dotfile in .[A-Za-z]*;
 do
@@ -19,8 +19,11 @@ do
     fi
 done
 
-cp karabiner.json ~/.config/karabiner/karabiner.json && echo "Karabiner config copied" || echo "Error while copying Karabiner"
-cp windows-binding.json ~/.config/karabiner/assets/complex_modifications/windows-binding.json && echo "Karabiner Complex Modification copied" || echo "Error while copying complex modification"
+if [ "$(uname)" = "Darwin" ]
+then
+    cp karabiner.json ~/.config/karabiner/karabiner.json && echo "Karabiner config copied" || echo "Error while copying Karabiner"
+    cp windows-binding.json ~/.config/karabiner/assets/complex_modifications/windows-binding.json && echo "Karabiner Complex Modification copied" || echo "Error while copying complex modification"
+fi
 
 ln -s $(pwd)/run-tmux.sh ~/run-tmux.sh || echo "Error while symlinking tmux startup script"
 
